[package]
name = "kafka-consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace = true}
rdkafka = {workspace = true}
kafka-config = {path = "../kafka-config"}
log = {workspace = true}